stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t your_image_name .

test:
  stage: test
  script:
    - docker run your_image_name npm test

deploy:
  stage: deploy
  script:
    - docker push your_registry/your_image_name
    - ssh your_server_address 'docker-compose -f /path/to/docker-compose.yml pull && docker-compose -f /path/to/docker-compose.yml up -d'
  only:
    - master
